export const DEFAULT_PAGE = 1;
export const MOVIES_FOR_HOMEPAGE_PER_GENRE = 5;
export const HERO_SECTION_ROTATION_INTERVAL = 5000;
export const GENRE_NAV_SCROLL_AMOUNT = 300;
export const GENRE_NAV_SCROLL_THRESHOLD = 10;
